### ISSUE TITLE
Changes after Zypher 3.2 Update

### ISSUE THREAD

**Issue by KohlRaphael** [GEIGEIGEIST/zmk-config-totem#3]
The Github Actions currently runs into an error and is unable to build the firmware. @coregano changed the totem.keymap files as required after the Zypher 3.2 update (https://github.com/coregano/zmk-config-totem/commit/1fcd5647fbf97159972546279981a054db1fae2c). Was able to build with these changes. However, untested on hardware.

**Comment by GEIGEIGEIST** [comment]
I fixed the issues. Should compile now.
